### ISSUE TITLE
Request: Edit Snippets

### ISSUE THREAD

**Issue by DracoClaw** [12944qwerty/css-toggler#3]
Allow the ability to edit saved snippets. This could mean no longer needing the default Themes page.

With the planned auto-update feature, do what Updater does and ask if you want to force update.

**Comment by GriefMoDz** [comment]
We're happy to announce that this request has successfully been fulfilled, whereas you can now make use of this feature once you've updated to the latest commit.

We'll also continue to work on the auto-update feature and will definitely take into consideration your suggestion regarding a similar force update action that is shipped with Powercord's built-in updater. Thank you.
